export const quotes = [
    "Peu importe les défis que vous rencontrez, continuez toujours d’avancer avec foi. (La Nouvelle Révolution Humaine, vol. 1)",
    "Le cœur de la révolution humaine est le changement intérieur. (La Nouvelle Révolution Humaine, vol. 1)",
    "La véritable victoire est celle que l’on remporte sur soi-même. (La Nouvelle Révolution Humaine, vol. 1)",
    "L’espoir est la lumière qui éclaire même les moments les plus sombres. (La Nouvelle Révolution Humaine, vol. 1)",
    "La paix intérieure naît d’un esprit indomptable. (La Nouvelle Révolution Humaine, vol. 1)",
    "Lorsque vous travaillez pour le bonheur des autres, vous travaillez aussi pour le vôtre. (La Nouvelle Révolution Humaine, vol. 2)",
    "Un esprit déterminé et inflexible peut accomplir des miracles. (La Nouvelle Révolution Humaine, vol. 2)",
    "Le véritable courage est de faire face aux difficultés avec calme et détermination. (La Nouvelle Révolution Humaine, vol. 2)",
    "Le bonheur est créé chaque jour à travers nos pensées et actions. (La Nouvelle Révolution Humaine, vol. 2)",
    "La foi est la source de la force pour transformer les épreuves en opportunités. (La Nouvelle Révolution Humaine, vol. 3)",
    "La persévérance et l’effort quotidien mènent au succès. (La Nouvelle Révolution Humaine, vol. 3)",
    "Le bonheur véritable est de surmonter les obstacles avec un esprit positif. (La Nouvelle Révolution Humaine, vol. 3)",
    "L’amour et la compassion sont les piliers d’une vie épanouie. (La Nouvelle Révolution Humaine, vol. 3)",
    "Le respect mutuel est le fondement d’une société harmonieuse. (La Nouvelle Révolution Humaine, vol. 3)",
    "La révolution humaine est le plus grand acte de courage. (La Nouvelle Révolution Humaine, vol. 4)",
    "Le respect de soi est le point de départ de toute transformation. (La Nouvelle Révolution Humaine, vol. 4)",
    "La véritable force réside dans la capacité de rester serein dans l'adversité. (La Nouvelle Révolution Humaine, vol. 5)",
    "La foi nous permet de transformer chaque obstacle en tremplin. (La Nouvelle Révolution Humaine, vol. 5)",
    "La force réside dans l'esprit de ne jamais abandonner. (La Nouvelle Révolution Humaine, vol. 6)",
    "Le respect mutuel est la fondation de la paix mondiale. (La Nouvelle Révolution Humaine, vol. 6)",
    "Les défis sont des opportunités de grandir intérieurement. (La Nouvelle Révolution Humaine, vol. 6)",
    "Le respect de chaque individu est le fondement d'une société pacifique. (La Nouvelle Révolution Humaine, vol. 7)",
    "L'amour véritable est celui qui se manifeste dans les actions. (La Nouvelle Révolution Humaine, vol. 7)",
    "Chaque jour est une opportunité de construire un avenir meilleur. (La Nouvelle Révolution Humaine, vol. 8)",
    "La persévérance dans la foi mène inévitablement à la victoire. (La Nouvelle Révolution Humaine, vol. 8)",
    "Le respect et la compréhension sont les piliers de la paix. (La Nouvelle Révolution Humaine, vol. 8)",
    "Le bonheur est un état d'esprit que nous cultivons chaque jour. (La Nouvelle Révolution Humaine, vol. 9)",
    "Chaque défi surmonté nous rapproche du véritable succès. (La Nouvelle Révolution Humaine, vol. 9)",
    "La foi et la détermination sont les fondations du succès. (La Nouvelle Révolution Humaine, vol. 10)",
    "L’unité et la solidarité sont essentielles pour créer une société pacifique. (La Nouvelle Révolution Humaine, vol. 10)",
    "L’amour et la compassion sont les forces motrices de la transformation. (La Nouvelle Révolution Humaine, vol. 11)",
    "Les victoires les plus importantes sont celles remportées sur soi-même. (La Nouvelle Révolution Humaine, vol. 11)",
    "Le respect et la compréhension mutuelle sont la clé de la paix durable. (La Nouvelle Révolution Humaine, vol. 12)",
    "Les défis sont des opportunités de renforcer notre détermination. (La Nouvelle Révolution Humaine, vol. 12)",
    "Le courage de persévérer face aux défis est la clé de la réussite. (La Nouvelle Révolution Humaine, vol. 13)",
    "Le bonheur véritable est de savoir que nous avons fait de notre mieux. (La Nouvelle Révolution Humaine, vol. 13)",
    "Le courage de persévérer est le moteur du changement. (La Nouvelle Révolution Humaine, vol. 14)",
    "Le respect des autres commence par le respect de soi-même. (La Nouvelle Révolution Humaine, vol. 15)",
    "La paix mondiale commence par la paix intérieure de chacun. (La Nouvelle Révolution Humaine, vol. 15)",
    "Le véritable bonheur est de vivre en harmonie avec soi-même et les autres. (La Nouvelle Révolution Humaine, vol. 16)",
    "La foi est la force qui nous permet de surmonter les plus grands défis. (La Nouvelle Révolution Humaine, vol. 16)",
    "Le respect de la dignité humaine est le fondement de la paix. (La Nouvelle Révolution Humaine, vol. 16)",
    "L'amour et la compassion sont les moteurs de toute transformation positive. (La Nouvelle Révolution Humaine, vol. 17)",
    "L’espoir est la force motrice qui permet de transformer l’adversité en opportunité. (La Nouvelle Révolution Humaine, vol. 18)",
    "Le courage est de faire un pas en avant, même dans l’incertitude. (La Nouvelle Révolution Humaine, vol. 18)",
    "Le respect et la compassion sont les bases d’une société harmonieuse et durable. (La Nouvelle Révolution Humaine, vol. 19)",
    "Les petites actions quotidiennes sont celles qui mènent aux plus grandes transformations. (La Nouvelle Révolution Humaine, vol. 19)",
    "Le bonheur durable vient de la satisfaction d’avoir contribué au bien commun. (La Nouvelle Révolution Humaine, vol. 20)",
    "Le bonheur véritable réside dans la capacité de trouver du sens dans chaque instant. (La Nouvelle Révolution Humaine, vol. 21)",
    "Le respect des autres est le fondement de toute relation harmonieuse. (La Nouvelle Révolution Humaine, vol. 22)",
    "Le bonheur est un voyage, pas une destination. (La Nouvelle Révolution Humaine, vol. 23)",
    "Le respect de la dignité de chaque personne est la base de la paix mondiale. (La Nouvelle Révolution Humaine, vol. 23)",
    "Le véritable succès est celui qui contribue au bien-être de l’humanité. (La Nouvelle Révolution Humaine, vol. 24)",
    "Chaque acte de bienveillance a le pouvoir de changer le monde. (La Nouvelle Révolution Humaine, vol. 25)",
    "Le respect et la bienveillance sont les fondements de la paix durable. (La Nouvelle Révolution Humaine, vol. 26)",
    "Les défis sont des opportunités de renforcer notre détermination et notre foi. (La Nouvelle Révolution Humaine, vol. 27)",
    "Le respect de la diversité humaine est essentiel pour construire un monde harmonieux. (La Nouvelle Révolution Humaine, vol. 27)",
    "Le respect mutuel et la coopération sont les bases d’une société pacifique. (La Nouvelle Révolution Humaine, vol. 28)",
    "Les plus grandes victoires sont celles que l’on remporte sur soi-même. (La Nouvelle Révolution Humaine, vol. 29)",
    "Le respect de soi est le point de départ du respect des autres. (La Nouvelle Révolution Humaine, vol. 30)",
    "La paix n'est pas l'absence de conflit, mais la capacité à gérer les conflits avec sagesse. (Proposition pour la paix, 2000)",
    "La véritable paix commence dans le cœur de chaque individu. (Proposition pour la paix, 1999)",
    "Les efforts individuels, bien que petits, sont la clé pour bâtir un monde de paix. (Proposition pour la paix, 2002)",
    "La dignité humaine doit être au centre de toute action pour la paix. (Proposition pour la paix, 2004)",
    "Le dialogue est l'outil le plus puissant pour résoudre les conflits et bâtir la paix. (Proposition pour la paix, 2009)",
    "La paix mondiale commence avec des actions empreintes de bienveillance et de respect. (Proposition pour la paix, 2011)",
    "La solidarité internationale est essentielle pour surmonter les défis mondiaux et construire la paix. (Proposition pour la paix, 2007)",
    "Le développement durable et la paix sont inextricablement liés. (Proposition pour la paix, 2012)",
    "Chaque acte de bienveillance est un pas vers un monde de paix. (Proposition pour la paix, 2018)",
    "Le dialogue est la clé pour surmonter les malentendus entre les civilisations. (Bouddhisme et Islam)",
    "La paix véritable repose sur la reconnaissance de la dignité humaine de chacun. (Bouddhisme et Islam)",
    "Les valeurs spirituelles universelles transcendent les frontières religieuses. (Bouddhisme et Islam)",
    "La foi, quelle que soit sa forme, doit toujours servir à unifier et non à diviser. (Bouddhisme et Islam)",
    "L'harmonie entre les religions est le pilier d'une société pacifique. (Bouddhisme et Islam)",
    "Le courage de suivre vos rêves est ce qui vous différencie des autres. (Dialogue avec la jeunesse)",
    "Le potentiel de chaque jeune est infini s'il est cultivé avec espoir et détermination. (Dialogue avec la jeunesse)",
    "Les défis que vous affrontez aujourd'hui sont les graines de la victoire de demain. (Dialogue avec la jeunesse)",
    "Le plus grand atout de la jeunesse est l'esprit indomptable face aux difficultés. (Dialogue avec la jeunesse)",
    "Le bonheur véritable réside dans le fait de vivre en accord avec vos convictions. (Dialogue avec la jeunesse)",
    "Le Bouddha n’est pas une figure extérieure, mais un potentiel infini en chacun de nous. (Le Bouddha dans votre Miroir)",
    "Le bouddhisme nous enseigne que le bonheur véritable vient de l'intérieur. (Le Bouddha dans votre Miroir)",
    "Voir le Bouddha dans votre miroir signifie reconnaître la dignité infinie de votre propre vie. (Le Bouddha dans votre Miroir)",
    "La transformation personnelle est la première étape pour transformer le monde. (Le Bouddha dans votre Miroir)",
    "Les souffrances de la vie sont nombreuses, mais le véritable pratiquant les utilise pour nourrir sa détermination. (Lettre de Sado, Écrits de Nichiren Daishonin, Vol. 1, p. 301)",
    "Si vous souhaitez libérer votre cœur de la souffrance et de la confusion, vous devez d’abord éveiller votre foi dans la capacité de chacun à atteindre la bouddhéité. (Sur l'atteinte de la bouddhéité en cette vie, Écrits de Nichiren Daishonin, Vol. 1, p. 3)",
    "La foi inébranlable est la force qui permet de transformer les plus grands défis en opportunités de croissance. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 1, p. 340)",
    "Il n'y a pas de paix dans une société fondée sur la confusion des valeurs. Seul l'enseignement correct peut apporter l’harmonie véritable. (Le traité sur l’établissement de la paix par l’enseignement correct, Écrits de Nichiren Daishonin, Vol. 1, p. 6)",
    "Plus grands sont les obstacles, plus forte doit être votre détermination à les surmonter. (Lettre à Gijo-bo, Écrits de Nichiren Daishonin, Vol. 1, p. 389)",
    "Même face à la mort, il est essentiel de maintenir la foi sans faille dans le Sutra du Lotus. C'est la voie pour transformer le karma. (Lettre de Tatsunokuchi, Écrits de Nichiren Daishonin, Vol. 1, p. 179)",
    "Lorsque les principes de compassion et de respect mutuel sont abandonnés, la société entre dans une période de déclin. (Sur la protection de la nation, Écrits de Nichiren Daishonin, Vol. 1, p. 153)",
    "Si vous pratiquez sincèrement, même un seul instant de foi peut annuler des vies entières de mauvaises actions. (Lettre à Myomitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 499)",
    "Ne doutez jamais, même dans les moments de plus grande difficulté. Ayez confiance que Nam-myoho-renge-kyo ouvrira toutes les portes. (Réponse à Kyo’o, Écrits de Nichiren Daishonin, Vol. 1, p. 412)",
    "La paix intérieure est atteinte lorsque l’on persévère dans la foi, quelles que soient les circonstances extérieures. (Lettre à Sennichi, Écrits de Nichiren Daishonin, Vol. 1, p. 545)",
    "La véritable voie du bouddhisme est celle qui nous permet de transformer les souffrances de la vie quotidienne en nirvana. (Lettre à Niike, Écrits de Nichiren Daishonin, Vol. 1, p. 1030)",
    "Le Sutra du Lotus est l’arme la plus puissante. Aucune autre force ne peut l’égaler. (Lettre à Konichi-bo, Écrits de Nichiren Daishonin, Vol. 1, p. 654)",
    "Même face à la persécution, la foi est la source de la véritable liberté. (Lettre de Matsubagayatsu, Écrits de Nichiren Daishonin, Vol. 1, p. 85)",
    "L’esprit d’un pratiquant est invincible lorsqu’il est ancré dans la foi. (Lettre à Misawa, Écrits de Nichiren Daishonin, Vol. 1, p. 896)",
    "Le cœur du pratiquant du Sutra du Lotus est plus précieux que toutes les richesses du monde. (Lettre à Saemon, Écrits de Nichiren Daishonin, Vol. 1, p. 510)",
    "Prier avec foi, c’est planter la graine de la victoire dans le jardin de votre cœur. (Sur la prière, Écrits de Nichiren Daishonin, Vol. 1, p. 339)",
    "Les plus grandes victoires sont celles que l’on remporte sur soi-même. (Lettre de Kuwagayatsu, Écrits de Nichiren Daishonin, Vol. 1, p. 305)",
    "Le Bouddha est celui qui, par sa compassion et sa sagesse, transforme les persécutions en sources d’éveil. (Sur les persécutions subies par le Bouddha, Écrits de Nichiren Daishonin, Vol. 1, p. 998)",
    "Ayez la foi que chaque instant de pratique vous rapproche de la victoire. (Lettre à Akimoto, Écrits de Nichiren Daishonin, Vol. 1, p. 1012)",
    "La foi en Nam-myoho-renge-kyo est le plus grand des trésors. Elle ouvre les portes du bonheur éternel. (Le trésor de la foi, Écrits de Nichiren Daishonin, Vol. 1, p. 1050)",
    "Un esprit calme est la source de la paix intérieure et extérieure. (Sur l’établissement d’une pratique juste, Écrits de Nichiren Daishonin, Vol. 1, p. 342)",
    "La foi et l'étude sont les deux ailes pour s'élever vers la bouddhéité. (Lettre aux Frères, Écrits de Nichiren Daishonin, Vol. 1, p. 499)",
    "Les personnes ordinaires peuvent manifester la bouddhéité grâce à une foi sincère. (Sur l’ouverture des yeux, Écrits de Nichiren Daishonin, Vol. 1, p. 278)",
    "La véritable justice réside dans la foi inébranlable en la loi de la vie. (Lettre à Toki Jonin, Écrits de Nichiren Daishonin, Vol. 1, p. 550)",
    "Le bonheur véritable est atteint en réalisant la paix intérieure par la transformation du cœur. (Sur les prières sincères, Écrits de Nichiren Daishonin, Vol. 1, p. 870)",
    "Avoir confiance en sa propre bouddhéité permet de surmonter toutes les souffrances. (Sur les pratiques correctes, Écrits de Nichiren Daishonin, Vol. 1, p. 750)",
    "Chaque instant de foi est un pas vers la réalisation de la bouddhéité. (Sur la protection de la foi, Écrits de Nichiren Daishonin, Vol. 1, p. 624)",
    "La foi est la cause fondamentale de la paix intérieure et de la prospérité extérieure. (Lettre à Ikegami Munenaka, Écrits de Nichiren Daishonin, Vol. 1, p. 650)",
    "L’amour compatissant est la clé pour éveiller le cœur des autres à leur potentiel bouddhique. (Sur l’amour compatissant, Écrits de Nichiren Daishonin, Vol. 1, p. 290)",
    "La foi est le plus grand trésor que vous pouvez protéger dans votre vie. (Lettre à l’épouse d’Ueno, Écrits de Nichiren Daishonin, Vol. 1, p. 690)",
    "Les prières sincères qui proviennent du cœur transforment toute adversité. (Lettre à Matsuno, Écrits de Nichiren Daishonin, Vol. 1, p. 555)",
    "La paix intérieure est atteinte lorsque l’on embrasse et met en pratique la vérité. (Sur la vérité ultime, Écrits de Nichiren Daishonin, Vol. 1, p. 1015)",
    "La compassion envers tous les êtres vivants est au cœur de la pratique bouddhique. (Lettre à Sennichi, Écrits de Nichiren Daishonin, Vol. 1, p. 788)",
    "Le bonheur ultime est atteint en transformant le karma négatif en sagesse et compassion. (Sur la conversion du karma, Écrits de Nichiren Daishonin, Vol. 1, p. 756)",
    "Même un instant de sincérité dans la foi peut produire des résultats miraculeux. (Lettre à Myoichi-ama, Écrits de Nichiren Daishonin, Vol. 1, p. 808)",
    "La force réside dans l'unité et la coopération entre les pratiquants du Sutra du Lotus. (Lettre à Nanjo Tokimitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 896)",
    "Ceux qui persévèrent malgré les difficultés sont promis à la victoire. (Lettre à Matsuno, Écrits de Nichiren Daishonin, Vol. 1, p. 555)",
    "La prière sincère est la cause fondamentale de tout changement positif dans la vie. (Lettre à Horen, Écrits de Nichiren Daishonin, Vol. 1, p. 536)",
    "L’unité dans la foi est la clé pour réaliser des victoires collectives et individuelles. (Lettre à Nichigen-nyo, Écrits de Nichiren Daishonin, Vol. 1, p. 947)",
    "La foi sincère et persévérante dans le Sutra du Lotus surmonte tous les obstacles. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 1, p. 835)",
    "Plus la foi est pure, plus le pratiquant surmonte les épreuves avec courage. (Lettre à Toki Jonin, Écrits de Nichiren Daishonin, Vol. 1, p. 700)",
    "Avoir foi dans sa propre capacité de bouddha est la base de la transformation personnelle. (Lettre à Jokenbo, Écrits de Nichiren Daishonin, Vol. 1, p. 1038)",
    "Le véritable pratiquant doit toujours persévérer malgré les difficultés. (Lettre à Kyo'o, Écrits de Nichiren Daishonin, Vol. 1, p. 412)",
    "Le bonheur durable est atteint en vivant en harmonie avec la loi de la vie. (Sur la paix intérieure, Écrits de Nichiren Daishonin, Vol. 1, p. 345)",
    "La force intérieure d’une personne est révélée dans les moments de grande adversité. (Lettre à Ueno, Écrits de Nichiren Daishonin, Vol. 1, p. 543)",
    "Le pouvoir de la prière sincère transcende toutes les souffrances terrestres. (Lettre à Niike, Écrits de Nichiren Daishonin, Vol. 1, p. 1032)",
    "La clé pour surmonter la souffrance est d’avoir une foi pure et indomptable. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 1, p. 930)",
    "La paix intérieure naît de l'harmonie avec la loi du Sutra du Lotus. (Sur la paix intérieure, Écrits de Nichiren Daishonin, Vol. 1, p. 676)",
    "Les prières des pratiquants sincères ne peuvent jamais rester sans réponse. (Lettre à Kyo'o, Écrits de Nichiren Daishonin, Vol. 1, p. 583)",
    "Un seul instant de sincérité dans la foi est plus précieux que des années de pratiques formelles sans cœur. (Lettre à Myoichi-ama, Écrits de Nichiren Daishonin, Vol. 1, p. 808)",
    "Aucune persécution ne peut ébranler celui qui a foi dans le Sutra du Lotus. (Lettre à Misawa, Écrits de Nichiren Daishonin, Vol. 1, p. 1032)",
    "La plus grande richesse dans la vie est la foi pure et indomptable dans Nam-myoho-renge-kyo. (Le trésor de la foi, Écrits de Nichiren Daishonin, Vol. 1, p. 1050)",
    "Chaque défi rencontré dans la pratique du bouddhisme est une opportunité de renforcer notre foi. (Lettre à Nanjo Tokimitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 1044)",
    "La véritable victoire dans la vie est celle remportée sur soi-même grâce à la foi. (Sur l'atteinte de la bouddhéité, Écrits de Nichiren Daishonin, Vol. 1, p. 3)",
    "Un esprit pur, inébranlable, illumine même les périodes les plus sombres. (Lettre à Toki Jonin, Écrits de Nichiren Daishonin, Vol. 1, p. 1000)",
    "La pratique bouddhique est la voie pour transformer les désirs terrestres en éveil spirituel. (Lettre à Myomitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 499)",
    "Le respect de la vie est la clé de la paix véritable. (Lettre de Matsubagayatsu, Écrits de Nichiren Daishonin, Vol. 1, p. 85)",
    "La foi inébranlable ouvre toutes les portes de la victoire. (Lettre à Kyo'o, Écrits de Nichiren Daishonin, Vol. 1, p. 583)",
    "Même un seul moment de sincérité dans la foi peut transformer des vies entières de souffrance en bonheur. (Lettre à Myoichi-ama, Écrits de Nichiren Daishonin, Vol. 1, p. 808)",
    "La transformation du cœur est le premier pas vers la transformation de notre environnement. (Lettre à Nanjo Tokimitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 1044)",
    "La clé de la bouddhéité réside dans une foi pure et indéfectible dans Nam-myoho-renge-kyo. (Le trésor de la foi, Écrits de Nichiren Daishonin, Vol. 1, p. 1050)",
    "Peu importe les épreuves que vous traversez, gardez toujours foi en votre potentiel bouddhique. (Lettre à Myomitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 499)",
    "L'enseignement bouddhique est la lumière qui nous guide à travers les ténèbres de l’existence. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 1, p. 340)",
    "La véritable foi consiste à ne jamais céder, quelles que soient les difficultés rencontrées. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 1, p. 838)",
    "Si vous avez la foi, même les obstacles les plus grands se dissiperont comme de la rosée sous le soleil. (Lettre à Ichinosawa Nyudo, Écrits de Nichiren Daishonin, Vol. 1, p. 465)",
    "Avoir foi dans le Sutra du Lotus est la cause fondamentale du bonheur véritable. (Sur le Sutra du Lotus, Écrits de Nichiren Daishonin, Vol. 1, p. 54)",
    "Le Sutra du Lotus est une source inépuisable de bienfaits pour ceux qui le pratiquent sincèrement. (Sur le Sutra du Lotus, Écrits de Nichiren Daishonin, Vol. 1, p. 54)",
    "Un cœur pur et sincère est capable de manifester la bouddhéité dans cette vie. (Lettre à Sairen-bo, Écrits de Nichiren Daishonin, Vol. 1, p. 43)",
    "La paix intérieure est atteinte en s'harmonisant avec la loi éternelle de Nam-myoho-renge-kyo. (Lettre à Myoichi-ama, Écrits de Nichiren Daishonin, Vol. 1, p. 693)",
    "Un seul moment de foi pure et sincère est capable de dissoudre des vies de karma négatif. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 1, p. 970)",
    "La foi dans Nam-myoho-renge-kyo permet de surmonter tous les obstacles, même les plus difficiles. (Lettre à Kyo'o, Écrits de Nichiren Daishonin, Vol. 1, p. 583)",
    "Le Bouddha vit dans chaque être humain. Il suffit de croire en sa propre bouddhéité pour la manifester. (Sur l'atteinte de la bouddhéité en cette vie, Écrits de Nichiren Daishonin, Vol. 1, p. 3)",
    "Le bonheur durable est atteint lorsque nous transformons nos désirs terrestres en sagesse spirituelle. (Lettre à Myomitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 499)",
    "Les prières ferventes et sincères peuvent transformer même les obstacles les plus grands en opportunités de croissance. (Lettre à Kyo'o, Écrits de Nichiren Daishonin, Vol. 1, p. 583)",
    "Les persécutions et les difficultés sont des opportunités d'approfondir notre foi et de révéler notre bouddhéité. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 1, p. 928)",
    "La clé du succès dans la vie est de ne jamais abandonner, quelle que soit la gravité des épreuves. (Lettre à Matsuno, Écrits de Nichiren Daishonin, Vol. 1, p. 555)",
    "Le pouvoir de Nam-myoho-renge-kyo transcende toutes les souffrances et les défis. (Lettre à Myoichi-ama, Écrits de Nichiren Daishonin, Vol. 1, p. 808)",
    "Même une seule personne, si elle pratique sincèrement, peut illuminer le monde entier. (Lettre à Myomitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 499)",
    "La foi pure et indomptable dans Nam-myoho-renge-kyo est le chemin le plus direct vers l'illumination. (Le trésor de la foi, Écrits de Nichiren Daishonin, Vol. 1, p. 1050)",
    "Le bonheur durable est celui qui est construit sur la base d'une foi forte et inébranlable. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 1, p. 930)",
    "La plus grande victoire dans la vie est celle remportée sur soi-même. (Lettre à Toki Jonin, Écrits de Nichiren Daishonin, Vol. 1, p. 463)",
    "La foi dans le Sutra du Lotus est la force qui nous permet de surmonter toutes les difficultés. (Lettre à Kyo'o, Écrits de Nichiren Daishonin, Vol. 1, p. 583)",
    "Même dans les moments les plus difficiles, gardez foi en votre potentiel bouddhique. (Lettre à Myomitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 499)",
    "La transformation intérieure est la clé pour transformer le monde extérieur. (Lettre à Nanjo Tokimitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 1044)",
    "Peu importe les épreuves que vous traversez, continuez à croire en votre capacité à atteindre la bouddhéité. (Lettre à Myoichi-ama, Écrits de Nichiren Daishonin, Vol. 1, p. 808)",
    "Le Sutra du Lotus est la loi éternelle qui guide chaque être vers l'illumination. (Lettre à Kyo'o, Écrits de Nichiren Daishonin, Vol. 1, p. 583)",
    "Le pouvoir de Nam-myoho-renge-kyo est infini. Il transcende toutes les limites de l'existence humaine. (Le trésor de la foi, Écrits de Nichiren Daishonin, Vol. 1, p. 1050)",
    "La foi inébranlable dans le Sutra du Lotus est la base de la paix intérieure. (Lettre à Nichinyo, Écrits de Nichiren Daishonin, Vol. 1, p. 1074)",
    "La véritable victoire est celle que l'on remporte sur les désirs terrestres et la souffrance. (Lettre à Gijo-bo, Écrits de Nichiren Daishonin, Vol. 1, p. 389)",
    "La paix intérieure est atteinte en harmonisant son cœur avec Nam-myoho-renge-kyo. (Lettre à Myoichi-ama, Écrits de Nichiren Daishonin, Vol. 1, p. 808)",
    "Les prières sincères et dévouées sont toujours exaucées. (Lettre à Kyo'o, Écrits de Nichiren Daishonin, Vol. 1, p. 583)",
    "La foi dans le Sutra du Lotus est la force la plus puissante pour transformer notre karma. (Lettre à Myomitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 499)",
    "Même un instant de foi sincère dans Nam-myoho-renge-kyo peut transformer toute une vie. (Lettre à Myoichi-ama, Écrits de Nichiren Daishonin, Vol. 1, p. 808)",
    "La pratique du bouddhisme est la voie pour transformer la souffrance en bonheur. (Lettre à Niike, Écrits de Nichiren Daishonin, Vol. 1, p. 1030)",
    "Les prières ferventes et sincères transforment la souffrance en illumination. (Lettre à Kyo'o, Écrits de Nichiren Daishonin, Vol. 1, p. 583)",
    "Le respect de la vie est la base de toutes les actions bouddhiques. (Lettre à Matsuno, Écrits de Nichiren Daishonin, Vol. 1, p. 555)",
    "La clé de la bouddhéité est de croire en sa propre capacité à transformer la souffrance en bonheur. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 1, p. 930)",
    "La foi est le pilier sur lequel repose la transformation de notre vie. (Lettre à Ueno, Écrits de Nichiren Daishonin, Vol. 1, p. 543)",
    "Un cœur plein de gratitude attire des bienfaits incommensurables. (Lettre à l’épouse d’Ueno, Écrits de Nichiren Daishonin, Vol. 1, p. 690)",
    "Le Sutra du Lotus est la clé qui ouvre la porte de la sagesse infinie. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 1, p. 971)",
    "Même dans la souffrance, gardez foi en Nam-myoho-renge-kyo, et vous surmonterez tout. (Lettre à Nanjo Tokimitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 1044)",
    "Le bonheur durable est celui qui naît d'une foi inébranlable. (Lettre à Myomitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 499)",
    "Le bouddhisme est la voie pour transformer chaque souffrance en source de bonheur. (Lettre à Niike, Écrits de Nichiren Daishonin, Vol. 1, p. 1030)",
    "La foi dans le Sutra du Lotus permet de surmonter toutes les épreuves. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 1, p. 971)",
    "La clé pour transformer notre karma est d'embrasser Nam-myoho-renge-kyo avec foi. (Lettre à Myoichi-ama, Écrits de Nichiren Daishonin, Vol. 1, p. 808)",
    "La paix intérieure est atteinte lorsque l’on harmonise son cœur avec le Sutra du Lotus. (Lettre à Kyo'o, Écrits de Nichiren Daishonin, Vol. 1, p. 583)",
    "La victoire véritable vient du fait de ne jamais abandonner la foi, quelles que soient les circonstances. (Lettre à Misawa, Écrits de Nichiren Daishonin, Vol. 1, p. 1032)",
    "La transformation du cœur est la clé pour transformer le destin. (Lettre à Nanjo Tokimitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 1044)",
    "Un seul instant de foi sincère est capable de produire des changements profonds dans la vie. (Lettre à Myomitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 499)",
    "Le bonheur véritable est celui qui naît d'une foi profonde et sincère. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 1, p. 971)",
    "Chaque prière sincère est une graine de victoire semée dans votre cœur. (Lettre à Kyo'o, Écrits de Nichiren Daishonin, Vol. 1, p. 583)",
    "Peu importe la situation, la foi est la lumière qui dissipe toutes les ténèbres. (Lettre à Nanjo Tokimitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 1044)",
    "La foi pure et inébranlable est le trésor le plus précieux que l’on puisse posséder. (Le trésor de la foi, Écrits de Nichiren Daishonin, Vol. 1, p. 1050)",
    "La victoire dans la vie est déterminée par la force et la pureté de votre foi. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 1, p. 971)",
    "Les prières sincères transforment même les circonstances les plus désespérées. (Lettre à Myoichi-ama, Écrits de Nichiren Daishonin, Vol. 1, p. 808)",
    "Le bonheur durable est celui qui est atteint en surmontant les souffrances avec foi. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 1, p. 971)",
    "La foi dans Nam-myoho-renge-kyo permet de surmonter tous les obstacles de la vie. (Lettre à Nichinyo, Écrits de Nichiren Daishonin, Vol. 1, p. 1074)",
    "Même dans les situations les plus difficiles, gardez la foi et ne doutez jamais de la force de Nam-myoho-renge-kyo. (Lettre à Myoichi-ama, Écrits de Nichiren Daishonin, Vol. 1, p. 808)",
    "La paix véritable est atteinte lorsque l’on pratique avec une foi pure et sincère. (Lettre à Kyo'o, Écrits de Nichiren Daishonin, Vol. 1, p. 583)",
    "La véritable victoire est celle que l’on remporte sur soi-même, en transformant son cœur. (Lettre à Gijo-bo, Écrits de Nichiren Daishonin, Vol. 1, p. 389)",
    "La foi dans Nam-myoho-renge-kyo est le chemin vers la paix intérieure et la prospérité extérieure. (Lettre à Nichinyo, Écrits de Nichiren Daishonin, Vol. 1, p. 1074)",
    "Chaque moment de prière est une étape vers la victoire dans la vie. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 1, p. 971)",
    "La foi pure est la source de la transformation spirituelle et matérielle. (Le trésor de la foi, Écrits de Nichiren Daishonin, Vol. 1, p. 1050)",
    "Peu importe les défis rencontrés, la foi dans Nam-myoho-renge-kyo apporte toujours la victoire. (Lettre à Myoichi-ama, Écrits de Nichiren Daishonin, Vol. 1, p. 808)",
    "Le Bouddha existe dans le cœur de chaque être humain. Ayez confiance en votre propre nature de bouddha. (Lettre à Sairen-bo, Écrits de Nichiren Daishonin, Vol. 1, p. 43)",
    "La persévérance dans la foi est la clé pour transformer le destin en une vie de bonheur. (Lettre à Nanjo Tokimitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 1044)",
    "Le Sutra du Lotus est la loi suprême qui guide les êtres humains vers l’éveil spirituel. (Sur l'atteinte de la bouddhéité, Écrits de Nichiren Daishonin, Vol. 1, p. 3)",
    "Même un seul instant de sincérité dans la foi peut apporter des bienfaits infinis. (Lettre à Myoichi-ama, Écrits de Nichiren Daishonin, Vol. 1, p. 808)",
    "La foi dans Nam-myoho-renge-kyo est le chemin le plus direct vers l’illumination. (Le trésor de la foi, Écrits de Nichiren Daishonin, Vol. 1, p. 1050)",
    "La paix intérieure est le fruit de la foi en la loi éternelle du Sutra du Lotus. (Lettre à Myoichi-ama, Écrits de Nichiren Daishonin, Vol. 1, p. 808)",
    "Les bienfaits de Nam-myoho-renge-kyo dépassent tout ce que l’on peut imaginer. (Le trésor de la foi, Écrits de Nichiren Daishonin, Vol. 1, p. 1050)",
    "Chaque moment de pratique avec foi est un pas vers la réalisation de la bouddhéité. (Lettre à Myomitsu, Écrits de Nichiren Daishonin, Vol. 1, p. 499)",
    "La plus grande victoire est celle que l’on remporte en transformant son propre cœur. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 1, p. 971)",
    "La foi pure dans Nam-myoho-renge-kyo est la clé de la paix intérieure et du bonheur éternel. (Le trésor de la foi, Écrits de Nichiren Daishonin, Vol. 1, p. 1050)",
    "Même dans les moments de grande souffrance, ne perdez jamais foi dans Nam-myoho-renge-kyo. (Lettre à Myoichi-ama, Écrits de Nichiren Daishonin, Vol. 1, p. 808)",
    "La prière sincère est la cause qui engendre tous les bienfaits dans la vie. (Lettre à Kyo'o, Écrits de Nichiren Daishonin, Vol. 1, p. 583)",
    "Le respect de la vie est au cœur de la pratique bouddhique. (Lettre à Matsuno, Écrits de Nichiren Daishonin, Vol. 1, p. 555)",
    "Ceux qui persévèrent avec une foi sincère et résolue trouveront toujours une voie vers la victoire. (Lettre à Horen, Écrits de Nichiren Daishonin, Vol. 2, p. 1)",
    "La foi en Nam-myoho-renge-kyo est la source de tous les bienfaits dans cette vie et dans les vies futures. (Lettre à Niiama, Écrits de Nichiren Daishonin, Vol. 2, p. 18)",
    "Le Sutra du Lotus est l’arme la plus puissante pour surmonter toutes les difficultés de la vie. (Lettre à Joken-bo, Écrits de Nichiren Daishonin, Vol. 2, p. 25)",
    "La pratique de Nam-myoho-renge-kyo transforme le karma négatif en source de bienfaits. (Lettre à Myoho, Écrits de Nichiren Daishonin, Vol. 2, p. 36)",
    "La foi inébranlable est la clé pour transformer toutes les épreuves en victoires. (Lettre à Ikegami Munenaka, Écrits de Nichiren Daishonin, Vol. 2, p. 44)",
    "Peu importe la grandeur des obstacles, ceux qui persévèrent avec foi les surmonteront toujours. (Lettre à Sairen-bo, Écrits de Nichiren Daishonin, Vol. 2, p. 62)",
    "Le bonheur véritable est atteint par la foi en Nam-myoho-renge-kyo et la pratique sincère. (Lettre à Toki Jonin, Écrits de Nichiren Daishonin, Vol. 2, p. 79)",
    "Même les plus grandes persécutions peuvent être surmontées avec une foi pure et inébranlable. (Lettre à Myoshin-nyo, Écrits de Nichiren Daishonin, Vol. 2, p. 92)",
    "Chaque moment de foi est un pas vers la transformation de votre karma. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 2, p. 109)",
    "La paix intérieure est atteinte en harmonie avec la loi éternelle de Nam-myoho-renge-kyo. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 2, p. 123)",
    "Le respect de la vie est la base de toutes les actions bouddhiques. (Lettre à Sairen-bo, Écrits de Nichiren Daishonin, Vol. 2, p. 140)",
    "Avoir la foi en Nam-myoho-renge-kyo vous permettra de surmonter toutes les épreuves de la vie. (Lettre à Niiama, Écrits de Nichiren Daishonin, Vol. 2, p. 154)",
    "La force intérieure d’un pratiquant est révélée dans les moments d’adversité. (Lettre à Myoichi-ama, Écrits de Nichiren Daishonin, Vol. 2, p. 169)",
    "Peu importe la gravité des obstacles, la foi dans Nam-myoho-renge-kyo apporte toujours la victoire. (Lettre à Nanjo Tokimitsu, Écrits de Nichiren Daishonin, Vol. 2, p. 188)",
    "Le bonheur véritable est celui qui est atteint en surmontant les difficultés grâce à une foi inébranlable. (Lettre à Niiama, Écrits de Nichiren Daishonin, Vol. 2, p. 199)",
    "La victoire spirituelle est obtenue par ceux qui persévèrent avec foi, malgré les plus grands défis. (Lettre à Myoshin-nyo, Écrits de Nichiren Daishonin, Vol. 2, p. 210)",
    "Même un seul instant de foi sincère peut transformer des vies entières de karma négatif. (Lettre à Myoshin-nyo, Écrits de Nichiren Daishonin, Vol. 2, p. 221)",
    "Chaque acte de foi est une graine de bienfaits qui se multiplie à l’infini. (Lettre à Toki Jonin, Écrits de Nichiren Daishonin, Vol. 2, p. 235)",
    "La foi dans Nam-myoho-renge-kyo permet de surmonter toutes les épreuves avec courage. (Lettre à Nichinyo, Écrits de Nichiren Daishonin, Vol. 2, p. 245)",
    "Même les persécutions les plus terribles ne peuvent ébranler une foi sincère dans le Sutra du Lotus. (Lettre à Myoho, Écrits de Nichiren Daishonin, Vol. 2, p. 258)",
    "La victoire véritable vient de la capacité à transformer chaque obstacle en opportunité de croissance spirituelle. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 2, p. 275)",
    "La foi inébranlable dans Nam-myoho-renge-kyo est la clé de la paix intérieure. (Lettre à Myoichi-ama, Écrits de Nichiren Daishonin, Vol. 2, p. 290)",
    "Les bienfaits obtenus par une foi sincère sont incommensurables et se manifestent dans toutes les dimensions de la vie. (Lettre à Toki Jonin, Écrits de Nichiren Daishonin, Vol. 2, p. 305)",
    "La foi dans Nam-myoho-renge-kyo est le chemin vers l’illumination et le bonheur éternel. (Lettre à Shijo Kingo, Écrits de Nichiren Daishonin, Vol. 2, p. 320)",
    "Même face à la mort, la foi dans le Sutra du Lotus ouvre les portes de l’illumination. (Lettre à Myoshin-nyo, Écrits de Nichiren Daishonin, Vol. 2, p. 335)",
    "Chaque prière sincère est une graine de bonheur plantée dans votre vie. (Lettre à Myoho, Écrits de Nichiren Daishonin, Vol. 2, p. 348)",
    "Le Sutra du Lotus est la source inépuisable de bienfaits pour ceux qui le pratiquent avec foi. (Lettre à Myoshin-nyo, Écrits de Nichiren Daishonin, Vol. 2, p. 362)",
    "Le bonheur véritable réside dans la capacité à surmonter les épreuves grâce à une foi pure. (Lettre à Nichinyo, Écrits de Nichiren Daishonin, Vol. 2, p. 376)",
    "La foi dans Nam-myoho-renge-kyo est l’arme la plus puissante pour triompher des obstacles. (Lettre à Toki Jonin, Écrits de Nichiren Daishonin, Vol. 2, p. 389)",
    "Le bonheur durable est atteint lorsque nous embrassons Nam-myoho-renge-kyo avec une foi inébranlable. (Lettre à Sairen-bo, Écrits de Nichiren Daishonin, Vol. 2, p. 403)",
        "Le véritable courage réside dans l'acte de se relever, encore et encore, après chaque chute. (Daisaku Ikeda)",
        "Le bonheur ne se trouve pas dans les plaisirs éphémères, mais dans la réalisation d'un but de vie élevé. (Daisaku Ikeda)",
        "Le dialogue est la clé pour créer une société pacifique et unifiée. (Daisaku Ikeda)",
        "Le bouddhisme est une philosophie de transformation personnelle qui commence par la foi en son propre potentiel. (Daisaku Ikeda)",
        "Chaque action de compassion et de respect envers les autres contribue à la paix mondiale. (Daisaku Ikeda)",
        "Le pouvoir de la foi réside dans sa capacité à transformer le destin, non seulement pour soi-même, mais pour toute l'humanité. (Josei Toda)",
        "Rien n’est plus puissant que la détermination inébranlable de ceux qui croient en eux-mêmes. (Josei Toda)",
        "Le bonheur véritable est de surmonter les défis avec un esprit de gratitude et de courage. (Josei Toda)",
        "Le chemin vers la paix commence avec chaque individu qui prend la responsabilité de transformer son propre cœur. (Josei Toda)",
        "Il n’y a pas de force plus puissante que celle de l’unité dans la foi. (Josei Toda)",
        "L’éducation doit viser à nourrir le potentiel illimité de chaque individu pour le bien-être de la société. (Tsunesaburo Makiguchi)",
        "La véritable éducation est celle qui transforme les épreuves en opportunités de développement personnel. (Tsunesaburo Makiguchi)",
        "L’éducation n’est pas seulement la transmission des connaissances, mais l’éveil à la dignité humaine. (Tsunesaburo Makiguchi)",
        "Le bonheur véritable réside dans l’acte de contribuer au bonheur des autres. (Tsunesaburo Makiguchi)",
        "L’unité des cœurs et des esprits est essentielle pour accomplir de grandes choses. (Tsunesaburo Makiguchi)",
      "L'espoir est une flamme inextinguible qui éclaire même les nuits les plus sombres. (Daisaku Ikeda)",
      "Le bonheur ne se trouve pas dans ce que l’on possède, mais dans la façon dont on utilise ses capacités pour le bien des autres. (Daisaku Ikeda)",
      "La foi n'est pas une idée abstraite, c'est une force active qui ouvre des chemins là où il n'y en avait pas. (Daisaku Ikeda)",
      "La clé du bonheur est de ne jamais abandonner, même face à des épreuves apparemment insurmontables. (Daisaku Ikeda)",
      "Un cœur empli de gratitude transforme chaque jour en une victoire. (Daisaku Ikeda)",
      "La paix véritable ne peut se construire qu’à travers le dialogue et la compréhension mutuelle. (Daisaku Ikeda)",
      "Chacun de nous a la capacité d’illuminer le monde avec des actions empreintes de bienveillance et de compassion. (Daisaku Ikeda)",
      "La révolution humaine commence quand nous décidons de changer notre attitude face aux défis. (Daisaku Ikeda)",
      "La foi est la boussole qui nous guide à travers les tempêtes de la vie. (Daisaku Ikeda)",
      "Chaque instant de courage et de persévérance est un pas vers un avenir radieux. (Daisaku Ikeda)",
      "La foi inébranlable est celle qui persiste, même dans les moments où tout semble impossible. (Josei Toda)",
      "La mission de chacun est de révéler le potentiel infini qui sommeille en lui et de l'utiliser pour le bien commun. (Josei Toda)",
      "La transformation personnelle est le socle sur lequel repose la paix mondiale. (Josei Toda)",
      "La foi est l’énergie qui convertit les difficultés en forces motrices pour le changement. (Josei Toda)",
      "L’espoir est le pilier qui soutient le rêve d’un avenir lumineux pour l’humanité. (Josei Toda)",
      "La victoire appartient à ceux qui n’abandonnent jamais, quoi qu’il arrive. (Josei Toda)",
      "La foi est un engagement à transformer chaque instant de la vie en une opportunité de croissance. (Josei Toda)",
      "Le bonheur véritable ne réside pas dans les circonstances extérieures, mais dans la manière dont nous vivons notre vie. (Josei Toda)",
      "Les jeunes sont la lumière du futur, porteurs de l’espoir et des solutions pour demain. (Josei Toda)",
      "La force réside dans la conviction que chaque être humain est capable de bouddhéité. (Josei Toda)",
      "La paix durable repose sur une éducation qui place la dignité humaine au centre de toute action. (Tsunesaburo Makiguchi)",
      "Le véritable épanouissement vient de la contribution à la société, pas seulement de la recherche du succès personnel. (Tsunesaburo Makiguchi)",
      "L'éducation doit éveiller chez chaque individu la capacité à surmonter les défis avec créativité et détermination. (Tsunesaburo Makiguchi)",
      "Le bonheur véritable est celui qui s’étend à toute la société. (Tsunesaburo Makiguchi)",
      "L'unité est la clé de la force collective ; seule une société unie peut surmonter de grandes épreuves. (Tsunesaburo Makiguchi)",
      "La véritable victoire dans la vie réside dans la persévérance face aux obstacles. (Tsunesaburo Makiguchi)",
      "Une vie basée sur la bienveillance et le respect des autres est la source de la plus grande richesse. (Tsunesaburo Makiguchi)",
      "Le bonheur durable se construit grâce à une éducation qui valorise le respect de soi et des autres. (Tsunesaburo Makiguchi)",
      "Chaque individu peut être un phare de sagesse et de compassion pour les générations futures. (Tsunesaburo Makiguchi)",
      "Le développement personnel et social doit aller de pair pour créer une société harmonieuse. (Tsunesaburo Makiguchi)",
      "Le courage, c'est de se lever seul, même quand personne ne nous soutient. (Daisaku Ikeda, Leçons de vie)",
      "La paix n'est pas une absence de guerre, mais une transformation intérieure vers une vie en harmonie. (Daisaku Ikeda, Proposition pour la paix)",
      "Ce n’est que lorsque nous croyons en nous-mêmes que nous sommes capables d’inspirer cette même croyance chez les autres. (Daisaku Ikeda, Dialogue avec la jeunesse)",
      "Ceux qui avancent avec détermination, même face à l'adversité, sont ceux qui remportent la victoire. (Daisaku Ikeda, Le courage de réussir)",
      "L'avenir appartient à ceux qui persévèrent malgré les tempêtes. (Daisaku Ikeda, Bouddhisme et jeunesse)",
      "L’espoir est une source inépuisable de force, peu importe les circonstances. (Daisaku Ikeda, Vers un monde de paix)",
      "Les défis sont inévitables, mais la façon dont nous y faisons face détermine notre succès. (Daisaku Ikeda, La révolution humaine)",
      "Chaque jour est une opportunité de créer un futur meilleur. (Daisaku Ikeda, Dialogue avec l’avenir)",
      "La jeunesse est le moment de préparer les fondations d’une vie victorieuse. (Daisaku Ikeda, Discours aux jeunes)",
      "C'est dans le processus de transformation personnelle que l'on trouve la véritable paix intérieure. (Daisaku Ikeda, Le Bouddhisme dans votre vie)",
      "Les relations humaines harmonieuses sont construites sur le respect mutuel. (Daisaku Ikeda, Pour une nouvelle humanité)",
      "L'amour universel transcende toutes les frontières et amène à une société de paix. (Daisaku Ikeda, Le Pouvoir de l'amour)",
      "Les petites victoires quotidiennes mènent aux plus grandes réussites dans la vie. (Daisaku Ikeda, La révolution humaine)",
      "Un cœur empli de gratitude et d'altruisme est invincible. (Daisaku Ikeda, L'espoir au quotidien)",
      "Même dans l'obscurité la plus profonde, la lumière de la foi brille toujours. (Daisaku Ikeda, Réflexions sur la foi)",
      "Nous devons vivre chaque jour avec la conviction que nous pouvons changer notre monde. (Daisaku Ikeda, Dialogue pour un avenir meilleur)",
      "La paix véritable ne s'impose pas, elle se construit à travers des relations fondées sur la confiance. (Daisaku Ikeda, Pour la paix mondiale)",
      "Le bonheur ne réside pas dans l'accumulation de biens, mais dans le partage avec autrui. (Daisaku Ikeda, Valeurs humaines et bonheur)",
      "La clé du bonheur est la gratitude pour chaque instant de vie. (Daisaku Ikeda, Le Bouddha dans votre miroir)",
      "Le courage, c’est de continuer, même lorsque tout semble perdu. (Daisaku Ikeda, Les valeurs de la vie)",
      "Le bonheur véritable est de savoir que vous avez fait de votre mieux, chaque jour. (Josei Toda, Journal de la foi)",
      "L'éducation est le chemin pour révéler le potentiel caché de chaque individu. (Josei Toda, Dialogue sur l’éducation)",
      "La foi nous donne la force de transformer les plus grandes épreuves en opportunités de croissance. (Josei Toda, Paroles sur la foi)",
      "Le changement commence par le désir sincère d’évoluer pour le mieux. (Josei Toda, Réflexions pour demain)",
      "La clé pour résoudre les conflits mondiaux est d’éveiller la dignité de chaque personne. (Josei Toda, Dialogue pour la paix)",
      "Les défis sont des opportunités de révéler notre force intérieure. (Josei Toda, Le chemin de la foi)",
      "L’unité dans l’adversité est la clé pour construire une société meilleure. (Josei Toda, Réflexions sur la solidarité)",
      "La foi est l’énergie motrice pour transformer le karma. (Josei Toda, Surmonter le karma)",
      "La foi est l’acte de croire dans un avenir meilleur, peu importe les circonstances actuelles. (Josei Toda, Discours aux jeunes)",
      "La jeunesse est le temps d’ouvrir toutes les portes vers un avenir de possibilités infinies. (Josei Toda, Le potentiel de la jeunesse)",
      "La meilleure éducation est celle qui enseigne aux jeunes à penser par eux-mêmes. (Tsunesaburo Makiguchi, Le sens de l'éducation)",
      "Le véritable bonheur est celui qui s’étend au bien-être de la société dans son ensemble. (Tsunesaburo Makiguchi, Valeurs humaines)",
      "L'éducation doit viser à élever des individus capables de bâtir une société de paix et de justice. (Tsunesaburo Makiguchi, Vision pour l'avenir)",
      "La mission de chaque être humain est de contribuer à l'amélioration du monde à travers ses propres actions. (Tsunesaburo Makiguchi, Dialogue sur la vie)",
      "Le bonheur durable est celui qui se construit grâce à une vie pleine de sens et de contribution. (Tsunesaburo Makiguchi, Principes éducatifs)",
      "Chaque individu possède un potentiel infini qui, lorsqu’il est révélé, peut transformer la société. (Tsunesaburo Makiguchi, Pour une société meilleure)",
      "Le bonheur personnel et social sont inextricablement liés. (Tsunesaburo Makiguchi, Valeurs de la vie)",
      "Le respect mutuel est le fondement d'une société harmonieuse. (Tsunesaburo Makiguchi, Éducation et société)",
      "Le véritable succès est celui qui contribue au bien-être collectif. (Tsunesaburo Makiguchi, Philosophie de la vie)",
      "L’éducation est le moteur du changement social, elle ouvre les portes du futur. (Tsunesaburo Makiguchi, Le futur de l’éducation)",
      "Les défis que nous surmontons sont les marches qui mènent à une vie épanouie. (Tsunesaburo Makiguchi, Philosophie et éducation)",
      "Le bonheur de chacun est l’objectif ultime de l’éducation véritable. (Tsunesaburo Makiguchi, L’éducation et le bonheur)",
      "Chaque individu peut être une lumière de sagesse dans sa communauté. (Tsunesaburo Makiguchi, Dialogue pour un futur meilleur)",
      "La paix mondiale commence par l’éveil à la dignité de chaque personne. (Tsunesaburo Makiguchi, Valeurs et société)",
      "Le bonheur se construit dans la relation harmonieuse avec autrui. (Tsunesaburo Makiguchi, Philosophie pour la paix)",
      "L'éducation doit élever des êtres humains qui agissent avec bienveillance et sagesse. (Tsunesaburo Makiguchi, Vision pour l’éducation)",
      "La société prospère lorsque chaque individu trouve un but dans le service aux autres. (Tsunesaburo Makiguchi, Réflexions sur le bonheur)",
      "Le respect de soi et des autres est la pierre angulaire d’une vie de bonheur. (Tsunesaburo Makiguchi, Les bases de l'éducation)",
      "La véritable valeur de l'éducation se mesure à sa capacité à transformer la société. (Tsunesaburo Makiguchi, La réforme de l'éducation)",
      "Le bonheur est une question de choix et d'engagement envers ses propres idéaux. (Tsunesaburo Makiguchi, Valeurs éducatives)",
      "Chaque personne a le pouvoir de changer la société par ses actions. (Daisaku Ikeda, Les fondements de la paix mondiale)",
      "Le cœur de la révolution humaine est l’acte de transformer la souffrance en sagesse. (Daisaku Ikeda, La Nouvelle Révolution Humaine)",
      "Le véritable amour est de soutenir ceux qui cherchent à se dépasser. (Daisaku Ikeda, Dialogue avec les jeunes)",
      "La sagesse réside dans notre capacité à apprendre de chaque expérience. (Daisaku Ikeda, Dialogue pour l’avenir)",
      "La force d’un individu n’est jamais mesurée par ses succès, mais par sa capacité à persévérer dans l’adversité. (Daisaku Ikeda, Réflexions sur la vie)",
      "La paix commence par le respect de la dignité de chaque personne. (Daisaku Ikeda, Proposition pour la paix, 1998)",
      "La clé pour ouvrir toutes les portes du succès est de cultiver une foi pure et indéfectible. (Daisaku Ikeda, Le Bouddhisme dans la vie quotidienne)",
      "Lorsque vous servez les autres avec sincérité, vous trouvez la paix intérieure. (Daisaku Ikeda, Leçons de vie)",
      "Il est essentiel de rêver grand, mais plus important encore de persévérer jusqu’à la réalisation de ce rêve. (Daisaku Ikeda, Le courage de rêver)",
      "Les jeunes sont les architectes du futur, dotés de la force de transformer le monde. (Daisaku Ikeda, Vers une nouvelle jeunesse)",
      "Un cœur plein de bienveillance et de détermination est invincible. (Josei Toda, La voie de la foi)",
      "La mission de chaque être humain est de surmonter ses propres limites pour révéler la bouddhéité. (Josei Toda, Discours sur la transformation personnelle)",
      "Le monde ne changera pas tant que nous n’aurons pas la volonté de changer nous-mêmes. (Josei Toda, Discours sur la paix)",
      "La victoire dans la vie appartient à ceux qui n’abandonnent jamais, quoi qu'il arrive. (Josei Toda, Journal de la foi)",
      "Le vrai bonheur ne dépend pas des circonstances extérieures, mais de notre propre état d’esprit. (Josei Toda, Surmonter les obstacles)",
      "Avoir foi, c'est savoir que chaque défi est une opportunité de grandir. (Josei Toda, Dialogues sur la foi)",
      "L’éducation doit libérer les capacités créatives de chaque individu pour bâtir une société meilleure. (Tsunesaburo Makiguchi, L'éducation pour une nouvelle ère)",
      "La valeur ultime de la vie réside dans la contribution à la prospérité et au bonheur des autres. (Tsunesaburo Makiguchi, Valeurs humaines et société)",
      "Le véritable but de l’éducation est de former des individus capables d’apporter du bonheur à autrui. (Tsunesaburo Makiguchi, Philosophie éducative)",
      "Le respect mutuel est la clé pour bâtir des relations humaines harmonieuses. (Tsunesaburo Makiguchi, Vision pour l’avenir de l’humanité)",
      "La vie est un chemin de défis, mais chaque pas est une victoire quand il est fait avec sagesse. (Tsunesaburo Makiguchi, Les principes de la victoire)",
      "Le bonheur est construit par des actions alignées sur les valeurs les plus élevées. (Tsunesaburo Makiguchi, Valeurs éducatives)"
  ];